### ISSUE TITLE
Optimize constant functions

### ISSUE THREAD

**Issue by paf31** [paf31/purescript-sdom#12]
Text nodes which never change don't need event handlers.

**Comment by Dierk** [comment]
shall that be a shortcut like
`verbatim s = text \_ _ -> s`
or shall the argument still be a function from context to string?

**Comment by paf31** [comment]
No, it would need to be a separate function entirely, one which doesn't add an event handler.

**Comment by paf31** [comment]
I've added `text_` to optimize text nodes this way, but constant attributes are still up for the same optimization. I'll make a new issue for that.
