### ISSUE TITLE
Support async event handlers?

### ISSUE THREAD

**Issue by chexxor** [paf31/purescript-sdom#2]
I don't use this lib yet, so no time constraint on responding to this issue. I've been looking at it a lot and am finding it great reference.

If I'm reading the code right, the eventListeners/handlers currently are synchronous. I wonder if Phil has already considered the async handler situation in this lib and precluded async handlers.

`(Event -> i -> o)`

It's inevitable that this lib will need to support async handlers. Maybe change the type of a handler to something like this:

``` purescript
type EventHandler m i o = (Event -> i -> ContT Unit m o)
-- Could prescribe `Run`. Surely no complaints - everyone likes trying a new thing. :-)
type EventHandlerRun effs i o = EventHandler (Run effs)
```

It would require updating `runStaticDOM` and I think it would be used like this:

``` purescript
element "button"
        (mempty)
        (singleton "click" \_ xs -> pure $ (length xs) : xs)
        -- or --
        (singleton "click" \_ xs -> do
          x <- fetchXInContT
          pure x : xs
        [ text $ const "+ Add" ]
```

**Comment by paf31** [comment]
I've put up an example [here](https://github.com/paf31/purescript-sdom/blob/c6321b47a519c7139d5e05499f81b38ec71c081f/examples/async/src/Main.purs).
